spring:
  application:
    name: raskub-auth-api
  security:
    oauth2:
      client:
        registration:
          google:
            authorization-grant-type: authorization_code
            scope:
              - openid
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            user-name-attribute: sub

app:
  client-id: abcdefghijklmnopqrstuvwxyz1234567890
  client-secret: rlagjstmd
  redirect-uri: http://localhost:8080/app/login

management:
  endpoint:
    configprops:
      show-values: always
  endpoints:
    web:
      exposure:
        include: health, configprops

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.web: DEBUG
