spring:
  cloud:
    kubernetes:
      enabled: true
      secrets:
        name: raskub-auth-api-secret
        enabled: true
        namespace: raskub-app
      config:
        enabled: false
  application:
    name: raskub-auth-api
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENTID}
            client-secret: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENTSECRET}
            redirect-uri: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_REDIRECTURI}
            authorization-grant-type: authorization_code
            scope:
              - openid
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            user-name-attribute: sub
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false

app:
  client-id: abcdefghijklmnopqrstuvwxyz1234567890
  client-secret: rlagjstmd
  redirect-uri: http://localhost:8080/app/login

api-key:
  header:
    client-name: ${APIKEY_HEADER_CLIENTNAME}
    client-id: ${APIKEY_HEADER_CLIENTID}
    client-secret: ${APIKEY_HEADER_CLIENTSECRET}
  services:
    common-api:
      client-name: ${APIKEY_SERVICES_COMMONAPI_CLIENTNAME}
      client-id: ${APIKEY_SERVICES_COMMONAPI_CLIENTID}
      client-secret: ${APIKEY_SERVICES_COMMONAPI_CLIENTSECRET}

management:
  endpoint:
    configprops:
      show-values: always
  endpoints:
    web:
      exposure:
        include: health, configprops

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.web: DEBUG
