spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENTID:default}
            client-secret: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENTSECRET:default}
            redirect-uri: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_REDIRECTURI:default}

api-key:
  header:
    client-name: ${APIKEY_HEADER_CLIENTNAME:default}
    client-id: ${APIKEY_HEADER_CLIENTID:default}
    client-secret: ${APIKEY_HEADER_CLIENTSECRET:default}
  services:
    common-api:
      client-name: ${APIKEY_SERVICES_COMMONAPI_CLIENTNAME:default}
      client-id: ${APIKEY_SERVICES_COMMONAPI_CLIENTID:default}
      client-secret: ${APIKEY_SERVICES_COMMONAPI_CLIENTSECRET:default}