CREATE SCHEMA auth;
GRANT USAGE ON SCHEMA auth TO devh;
GRANT CREATE ON SCHEMA auth TO devh;

CREATE TABLE auth.google_oauth2_user
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email       VARCHAR(255) NOT NULL UNIQUE,
    name        VARCHAR(255),
    picture_url VARCHAR(255),
    sub         VARCHAR(255) NOT NULL UNIQUE,
    user_id     VARCHAR(255) NOT NULL UNIQUE
);
ALTER TABLE auth.google_oauth2_user owner TO devh;

CREATE TABLE auth.credentials
(
    client_secret_modified_date date         NOT NULL,
    expiry_days                 bigint       NOT NULL,
    id                          bigint       NOT NULL PRIMARY KEY,
    client_id                   VARCHAR(255) NOT NULL,
    client_name                 VARCHAR(255) NOT NULL UNIQUE,
    client_secret               VARCHAR(255) NOT NULL
);
ALTER TABLE auth.credentials owner TO devh;