apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: raskub-auth-api-role
  namespace: raskub-app
subjects:
  - kind: ServiceAccount
    name: raskub-auth-api-sa
    apiGroup: ""
roleRef:
  kind: Role
  name: raskub-auth-api-reader
  apiGroup: rbac.authorization.k8s.io